In [162]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error

In [97]:
import numpy as np
import pandas as pd
import random
rng = np.random.default_rng(1)
z = np.array(['Red', 'White', 'Blue', 'Blue', 'Red', 'Red'])
x = rng.integers(100,1000,10)
y = rng.choice([True, False], size =10, p=[0.7,0.3])
x, y, z

(array([525, 560, 779, 955, 131, 229, 840, 953, 324, 380]),
 array([ True, False,  True,  True,  True, False,  True,  True, False,
         True]),
 array(['Red', 'White', 'Blue', 'Blue', 'Red', 'Red'], dtype='<U5'))

In [102]:
data ={'Obs': [1,2,3,4,5,6],'X1':[0,2,0,0,-1,1], 'X2':[3,0,1,1,0,1], 'X3':[0,0,3,2,1,1], 'Y':['Red', 'Red', 'Red', 'Green', 'Green', 'Red']}
df = pd.DataFrame(data)
df = df.set_index('Obs')

X1  X2  X3      Y
Obs                   
1     0   3   0    Red
2     2   0   0    Red
3     0   1   3    Red
4     0   1   2  Green
5    -1   0   1  Green
6     1   1   1    Red

In [143]:
#Split dataset into training and testing sets
X = df[['X1','X2','X3']]
y = df['Y']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=50)

In [144]:
#Create knn classifier
knn = KNeighborsClassifier(n_neighbors = 3)

In [145]:
#Train model
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [146]:
#Make predictions  
y_pred = knn.predict(X_test)
y_pred
#print('Accuracy:', accuracy_score(y_test, y_pred))
#print('Classification Report:')
#print(classification_report(y_test, y_pred))

array(['Red', 'Red'], dtype=object)

In [151]:
Advertising= pd.read_csv('Advertising.csv')
Advertising

ID     TV  Radio  Newspaper  Sales
0      1  230.1   37.8       69.2   22.1
1      2   44.5   39.3       45.1   10.4
2      3   17.2   45.9       69.3    9.3
3      4  151.5   41.3       58.5   18.5
4      5  180.8   10.8       58.4   12.9
..   ...    ...    ...        ...    ...
195  196   38.2    3.7       13.8    7.6
196  197   94.2    4.9        8.1    9.7
197  198  177.0    9.3        6.4   12.8
198  199  283.6   42.0       66.2   25.5
199  200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [157]:
#Split dataset into training and testing sets
X = Advertising[['TV', 'Radio', 'Newspaper']]
y = Advertising['Sales']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [160]:
#Create knn classifier
knn = KNeighborsRegressor(n_neighbors = 3)

#Train model
knn.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [161]:
#Make predictions  
y_pred = knn.predict(X_test)
y_pred

array([ 9.26666667, 16.1       ,  5.93333333,  9.36666667,  7.76666667,
       22.9       , 23.73333333, 18.93333333, 11.36666667, 13.8       ,
       15.3       ,  6.96666667, 14.93333333,  6.6       , 13.36666667,
        8.93333333, 11.53333333,  9.66666667,  7.53333333, 20.43333333,
        3.36666667, 21.7       , 16.13333333, 13.6       ,  7.8       ,
        8.6       , 18.3       , 13.56666667, 10.83333333, 20.9       ,
        7.36666667, 18.7       ,  9.96666667, 10.03333333, 13.23333333,
        9.63333333,  9.66666667, 16.13333333, 11.7       , 22.46666667])

In [164]:
#Evaluate model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f'Root mean square error: {rmse:.2f}')

Root mean square error: 1.40


In [169]:
#Make new predition
milo = pd.DataFrame({'TV': [8900], 'Radio': [200], 'Newspaper':[500]})
Predict_milo_sale = knn.predict(milo)
print(f'Predicted Milo Sale: ${Predict_milo_sale[0]:.2f}')

Predicted Milo Sale: $21.97


In [180]:
#Trying it another way: by using part of the data for further prediction


#Reducing the size of data
Advertised = Advertising[:101]

#Split dataset into training and testing sets
X = Advertised[['TV', 'Radio', 'Newspaper']]
y = Advertised['Sales']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [182]:
#Create knn classifier
knn = KNeighborsRegressor(n_neighbors = 3)

#Train model
knn.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [184]:
#Make predictions  
y_pred = knn.predict(X_test)
y_pred

array([11.16666667, 20.9       , 10.46666667, 18.43333333, 14.4       ,
       15.8       , 11.83333333, 13.        , 22.6       , 21.3       ,
       19.26666667, 16.76666667,  7.86666667, 11.33333333, 12.7       ,
        8.36666667, 11.2       , 14.63333333, 24.66666667,  8.7       ,
       15.7       ])

In [187]:
#Evaluate model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f'Root mean square error: {rmse:.2f}')

Root mean square error: 1.45


In [199]:
#Make new predition
milo = pd.DataFrame({'TV': [8900], 'Radio': [200], 'Newspaper':[500]})
Predict_milo_sale = knn.predict(milo)
print(f'Predicted Milo Sale: ${Predict_milo_sale[0]:.2f}')

Predicted Milo Sale: $19.63


In [220]:
#make new prediction from the sample data
z = Advertising[199:]
milo = z[['TV', 'Radio', 'Newspaper']]
Predict_milo_sale = knn.predict(milo)
print(f'Predicted Milo Sale: ${Predict_milo_sale[0]:.2f}')

Predicted Milo Sale: $14.63


In [221]:
#Trying a simple regression

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler